http://localhost:5000/api/products

###
GET http://localhost:5000/api/prices/search?query=&sort=&verifiedOnly=true

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "[EMAIL_ADDRESS]",
    "password": "[PASSWORD]"
}

###

POST http://localhost:5000/api/discrepancy
Content-Type: application/json

{
    "priceId": "1",
    "reason": "Price is too low"
}